# Generated by Django 5.2 on 2025-05-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
    ]
