# Generated by Django 5.2 on 2025-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='template',
            field=models.CharField(blank=True, help_text='Template name to render this feature', max_length=100, null=True),
        ),
    ]
