# Generated by Django 5.2 on 2025-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_feature_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='url',
            field=models.CharField(blank=True, help_text='URL for this feature', max_length=200, null=True),
        ),
    ]
