# Generated by Django 5.2.1 on 2025-05-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_feature_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='url',
        ),
    ]
