# Generated by Django 5.2.1 on 2025-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_feature_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='template',
        ),
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_url',
            field=models.URLField(),
        ),
    ]
