# Generated by Django 5.2 on 2025-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_feature_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category for grouping FAQs', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='You can use basic HTML tags for formatting'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, help_text='Controls the display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
