# Generated by Django 5.2 on 2025-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_newsletter_faq_category_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When a response was sent', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last newsletter was sent', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscription_source',
            field=models.CharField(blank=True, help_text='Where the subscription came from (e.g., footer, popup)', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Email address of the sender', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether this message has been read by an admin'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Content of the message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Name of the sender', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='Subject of the message', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(help_text='Description of the feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(help_text='Font Awesome or Bootstrap icon class (e.g., fa-chart-line, bi-graph-up)', max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this feature is currently displayed'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(help_text='Title of the feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the hero section (recommended size: 1920x1080px)', null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_text',
            field=models.CharField(blank=True, help_text='Text for the call-to-action button (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_url',
            field=models.URLField(blank=True, help_text='URL for the call-to-action button (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this hero section is currently displayed'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(help_text='Subheading or description text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(help_text='Main heading for the hero section', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(help_text='Email address for the subscription', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this subscription is currently active'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(help_text='The testimonial text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(help_text='Photo of the person (recommended size: 200x200px, square)', upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this testimonial is currently displayed'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Name of the person giving the testimonial', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(help_text='Job title or role of the person', max_length=100),
        ),
    ]
