# Generated by Django 5.2 on 2025-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='submitted_by',
            field=models.CharField(blank=True, help_text='Username of the person who submitted this question', max_length=150),
        ),
    ]
