# Generated by Django 5.2 on 2025-05-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_faq_submitted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
