# Generated by Django 5.2 on 2025-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0005_remove_category_is_active_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.PositiveIntegerField()),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('saving', 'Tabungan'), ('investment', 'Investasi'), ('purchase', 'Pembelian'), ('debt', 'Pembayaran Utang'), ('other', 'Lainnya')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
