# Generated by Django 5.2 on 2025-05-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('sugar', models.FloatField()),
                ('is_caffeinated', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtracker.category')),
            ],
        ),
    ]
