# Generated by Django 5.2 on 2025-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealtracker', '0002_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='is_caffeinated',
            field=models.BooleanField(default=False),
        ),
    ]
