# Generated by Django 5.2 on 2025-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealtracker', '0003_alter_drink_is_caffeinated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommended_calories', models.IntegerField(blank=True, null=True)),
                ('suitable_for', models.CharField(blank=True, max_length=200, null=True)),
                ('not_suitable_for', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
