# Generated by Django 5.2 on 2025-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealtracker', '0004_diettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('severity', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Critical')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avoid_items/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
