# Generated by Django 5.2 on 2025-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesstracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Build Muscle', 'Build Muscle'), ('Increase Stamina', 'Increase Stamina'), ('Improve Flexibility', 'Improve Flexibility'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
