# Generated by Django 5.2 on 2025-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0002_userprofile_dashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text='Your current company or organization', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Your hobbies and interests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your current location/city', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, help_text='Your current profession or job title', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, help_text='Your social media profiles'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal or business website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Your home or office address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your contact number', max_length=20),
        ),
    ]
