# Generated by Django 5.2 on 2025-05-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0003_userprofile_company_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardLayout',
        ),
        migrations.DeleteModel(
            name='DashboardNotification',
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
