# Generated by Django 5.2 on 2025-05-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0005_remove_userprofile_notification_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardbookmark',
            options={'ordering': ['-is_favorite', '-created_at'], 'verbose_name': 'Dashboard Bookmark', 'verbose_name_plural': 'Dashboard Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='dashboardnote',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Dashboard Note', 'verbose_name_plural': 'Dashboard Notes'},
        ),
        migrations.AlterModelOptions(
            name='dashboardreminder',
            options={'ordering': ['is_completed', 'due_date'], 'verbose_name': 'Dashboard Reminder', 'verbose_name_plural': 'Dashboard Reminders'},
        ),
        migrations.AlterModelOptions(
            name='dashboardshortcut',
            options={'ordering': ['shortcut_key'], 'verbose_name': 'Dashboard Shortcut', 'verbose_name_plural': 'Dashboard Shortcuts'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-last_activity'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='repeat_interval',
            field=models.IntegerField(blank=True, help_text='Interval in days for repeating reminders', null=True),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='action',
            field=models.CharField(help_text='URL or action to perform', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='icon',
            field=models.CharField(help_text='FontAwesome icon class (e.g., fa-home)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='shortcut_key',
            field=models.CharField(help_text='Keyboard shortcut (e.g., Ctrl+H)', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
