# Generated by Django 5.2 on 2025-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0006_alter_dashboardbookmark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='category',
            field=models.CharField(blank=True, help_text='Category for organizing bookmarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the bookmark'),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as a favorite for quick access'),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='title',
            field=models.CharField(help_text='Name of the bookmark', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='url',
            field=models.URLField(help_text='URL of the bookmark'),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='category',
            field=models.CharField(blank=True, help_text='Category for organizing notes', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='content',
            field=models.TextField(help_text='Content of the note'),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin note to top of list'),
        ),
        migrations.AlterField(
            model_name='dashboardnote',
            name='title',
            field=models.CharField(help_text='Title of the note', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or details'),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='due_date',
            field=models.DateTimeField(help_text='When the reminder is due'),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark if the reminder has been completed'),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='reminder_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Interval')], help_text='Type of reminder recurrence', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardreminder',
            name='title',
            field=models.CharField(help_text='Title of the reminder', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what the shortcut does'),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the shortcut is currently active'),
        ),
        migrations.AlterField(
            model_name='dashboardshortcut',
            name='title',
            field=models.CharField(help_text='Name of the shortcut', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('IDR', 'Indonesian Rupiah'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('SGD', 'Singapore Dollar')], default='USD', max_length=3),
        ),
    ]
