# Generated by Django 5.2 on 2025-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0007_alter_dashboardbookmark_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='Content of the message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this message has been read by an admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When a response was sent', null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='You can use basic HTML tags for formatting')),
                ('category', models.CharField(blank=True, help_text='Optional category for grouping FAQs', max_length=100)),
                ('submitted_by', models.CharField(blank=True, help_text='Username of the person who submitted this question', max_length=150)),
                ('order', models.IntegerField(default=0, help_text='Controls the display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the feature', max_length=100)),
                ('description', models.TextField(help_text='Description of the feature')),
                ('icon', models.CharField(help_text='Font Awesome or Bootstrap icon class (e.g., fa-chart-line, bi-graph-up)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the hero section', max_length=200)),
                ('subtitle', models.TextField(help_text='Subheading or description text')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the hero section (recommended size: 1920x1080px)', null=True, upload_to='hero_images/')),
                ('call_to_action_text', models.CharField(blank=True, help_text='Text for the call-to-action button (optional)', max_length=100, null=True)),
                ('call_to_action_url', models.URLField(blank=True, help_text='URL for the call-to-action button (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero section is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for the subscription', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='When the last newsletter was sent', null=True)),
                ('subscription_source', models.CharField(blank=True, help_text='Where the subscription came from (e.g., footer, popup)', max_length=50)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('role', models.CharField(help_text='Job title or role of the person', max_length=100)),
                ('content', models.TextField(help_text='The testimonial text')),
                ('image', models.ImageField(help_text='Photo of the person (recommended size: 200x200px, square)', upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this testimonial is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
