# Generated by Django 5.2 on 2025-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0008_contactmessage_faq_feature_herosection_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='call_to_action_url',
            field=models.CharField(blank=True, help_text='URL for the call-to-action button (can be internal path like /register or external URL)', max_length=200, null=True),
        ),
    ]
