# Generated by Django 5.2.1 on 2025-05-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0009_alter_herosection_call_to_action_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image',
            new_name='testimonial_image',
        ),
    ]
