# Generated by Django 5.2.1 on 2025-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardmanager', '0010_rename_image_testimonial_testimonial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial_image',
            new_name='image',
        ),
    ]
